version: "3"

services:
  db:
    image: postgres:10.10
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./db/data:/tmp/db.dump.testdb

#  X    POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8 "
#      PGDATA: /tmp/dump
