version: "3"

services:
  db:
    image: postgres:10.10
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      IMPORT_FROM_DIR: /data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./db/sh:/docker-entrypoint-initdb.d
      - ./db/data:/data

#      POSTGRES_DB: testdb
#      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8 "
#      PGDATA: /tmp/dump
