version: "3"

services:
  db:
#    image: postgres:10.10-alpine
    image: postgres:10.10
    container_name: postgresql
    ports:
      - 5433:5432
    environment:
      IMPORT_FROM_DIR: /tmp/initdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: test2db
    volumes:
      - ./docker/initsh:/docker-entrypoint-initdb.d
      - ./docker/initdata:/tmp/initdata

#  X    POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8 "
#      PGDATA: /tmp/dump
